plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace = 'com.databits.androidscouting.core.data'
    compileSdk = 36

    defaultConfig {
        minSdk = 26
    }

    compileOptions {
        sourceCompatibility = 21
        targetCompatibility = 21
    }

    kotlinOptions {
        jvmTarget = '21'
    }
}

dependencies {
    implementation project(':core-model')
    implementation project(':core-domain')

    testImplementation 'junit:junit:4.13.2'
}
